# Generated by Django 3.2.6 on 2021-10-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='person_number',
            field=models.IntegerField(),
        ),
    ]
