# Generated by Django 3.2.6 on 2021-10-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_site', '0002_alter_contacts_person_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='person_email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='person_l_name',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='person_message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='person_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='person_number',
            new_name='Number',
        ),
    ]
