# Generated by Django 3.2.6 on 2021-10-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_site', '0003_auto_20211009_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='Number',
            new_name='Age',
        ),
    ]
